apiVersion: v1
kind: Service
metadata:
  name: ktor-sample-svc
  labels:
    revision: "{{ .Values.revision }}"
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    name: ktor-sample