apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: skaffold
spec:
  params:
    - name: pathToSkaffoldDir
      type: string
      description: The path to the skaffold.yaml directory 
    - name: command 
      type: string
      description: skaffold command
      default: build
    - name: args
      type: string
      description: args of skaffold command 
  workspaces:
    - name: source
  steps:
    - image: gcr.io/k8s-skaffold/skaffold:v1.37.0
      name: execute-skaffold-command 
      command: ["skaffold", "$(params.command)"]
      workingDir: "$(workspaces.source.path)/$(params.pathToSkaffoldDir)"
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: docker:20.10.13-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}